### ISSUE TITLE
[Issue] InvokeAI wont launch

### ISSUE THREAD

**Issue by aegisnir** [diStyApps/seait#34] opened 2023-07-22 18:33 UTC
Just installed InvokeAI and went through all the steps in the terminal to configure it.  When I go to launch it, nothing happens.  It tried to launch but encounters an error.  I am unable to locate invoke.bat to try and launch it manually.

Terminal output after attempting to upgrade and launch:
```
Updating InvokeAI at D:\ai\InvokeAI
Already up to date.
launching InvokeAI at D:\ai\InvokeAI
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[2023-07-22 14:31:13,753]::[InvokeAI]::INFO --> Patchmatch initialized
D:\ai\InvokeAI\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[2023-07-22 14:31:13,988]::[InvokeAI]::INFO --> InvokeAI version 3.0.0
[2023-07-22 14:31:14,010]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce RTX 3080 Ti
[2023-07-22 14:31:14,024]::[InvokeAI]::INFO --> Scanning C:\Users\USERNAME\invokeai\models for new models
[2023-07-22 14:31:14,405]::[InvokeAI]::INFO --> Scanned 0 files and directories, imported 0 models
[2023-07-22 14:31:14,417]::[InvokeAI]::INFO --> Model manager service initialized
[2023-07-22 14:31:14,422]::[InvokeAI]::INFO --> InvokeAI database location is "C:\Users\USERNAME\invokeai\databases\invokeai.db"
invoke>
```

**Comment by AsaTyr2018** [comment] 2023-08-16 15:33
Can you try to install InvokeAI in a different folder then your home folder? (C:\Users\USERNAME\invokeai\)
As example: C:\AI\invokeai\
1. Enter Path
2. Select "Set Path"
3. Activated

![grafik](https://github.com/diStyApps/seait/assets/43162495/7d0c6445-8f0b-421f-9c40-ae68cf1e7d95)

**Comment by aegisnir** [comment] 2023-08-16 15:40
Sorry I’m on Linux so no c drive and I’m doing it in CLI so no gui.  I’ll play around with it a bit more this weekend

**Comment by AsaTyr2018** [comment] 2023-08-30 21:13
@aegisnir Did it work? Please Update

**Comment by AsaTyr2018** [comment] 2023-09-02 22:32
@aegisnir since we got no reply, i would close this issue. 
If the Problem is still active, please open a new Ticket

**Closed by AsaTyr2018** 2023-09-02 22:32 UTC
Labels: Issue
